name: Build and Release PyQt5 Application

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        # Install your project dependencies
        pip install -r requirements.txt
      shell: powershell

    - name: Build with PyInstaller
      run: |
        pyinstaller AutoCreditation.spec

    - name: Prepare artifacts
      run: |
        mkdir release
        copy dist\AutoCreditation.exe release\AutoCreditation.exe
      shell: cmd

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: release/

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts/

    - name: Prepare release files
      run: |
        mkdir -p release-files
        find artifacts/ -type f -exec cp {} release-files/ \;
        ls -la release-files/

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: release-files/*
        draft: false
        prerelease: false
        generate_release_notes: true
        name: Release ${{ github.ref_name }}
        body: |
          ## Changes in this Release

          - Built automatically from tag ${{ github.ref_name }}
          - Windows executable included

          ## Download Instructions

          - **Windows**: Download `AutoCreditation.exe` and run directly

          ## System Requirements

          - Windows 10 or later (64-bit)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Optional: Create latest release (overwrites previous latest)
  update-latest:
    needs: release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Update latest release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        files: artifacts/*/*
        draft: false
        prerelease: false
        name: Latest Release
        body: |
          This is the latest stable release.

          **Note**: This release is automatically updated with each new version tag.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}